spring.application.name=diet_app

# Database Configuration (Local PostgreSQL for Development)
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.tmvnhpdgqdcyslxuwots
spring.datasource.password=E0v43W88UUZgcIzY
spring.datasource.driver-class-name=org.postgresql.Driver
# Database Configuration
#spring.datasource.url=jdbc:postgresql://localhost:5433/diet_app?createDatabaseIfNotExist=true
#spring.datasource.username=postgres
#spring.datasource.password=Tarunnsr@123
#spring.datasource.driver-class-name=org.postgresql.Driver
# Supabase Configuration (Production):
# spring.datasource.url=jdbc:postgresql://db.tmvnhpdgqdcyslxuwots.supabase.co:5432/postgres?sslmode=require
# spring.datasource.username=postgres
# spring.datasource.password=Tarunnsr@123

# JPA / Hibernate
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Server Configuration
server.port=8085

# jwt
app.jwt.secret=hw4394-t498v/rjfuwg84vserncueshfhsi4r
app.jwt.expiry=86400000

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tarunsharma87289@gmail.com
spring.mail.password=deipfzblmyrjiltj

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Razorpay configuration
razorpay.key.id=rzp_test_T57g4rbnzF38Zh
razorpay.key.secret=Y8X46wl0J2G7gxZvbzWcSDB9

